### ISSUE TITLE
print time bug

### ISSUE THREAD

**Issue by Rishabh-Kumar-Bothra** [geekychaser/Print_Slip#1]
While printing the slip k shifts down.
![screenshot from 2017-09-29 02-11-54](https://user-images.githubusercontent.com/24489162/30989541-9581fd98-a48d-11e7-935a-bc73632e6f71.png)

**Comment by rbrishabh** [comment]
used:
 h2::first-letter {
    margin-top: 0;
}
to fix issue. issue resolved.

**Comment by Rishabh-Kumar-Bothra** [comment]
@rbrishabh no need of showing the code you changed. Simply write issue fixed with little bit of description. :)
